# config.py
# ─────────────────────────────────────────────
# Central place for all tunable parameters.
# Change values here — never hunt through logic files.
# ─────────────────────────────────────────────

# --- Model ---
MODEL_PATH = "yolov8n.pt"       # 'n' = nano, fastest on CPU
                                 # Options: n, s, m, l, x (speed vs accuracy)
CONFIDENCE_THRESHOLD = 0.15       # Below this, detections are ignored
                                 # Lower = more detections, more false positives
                                 # Higher = fewer detections, more misses

# --- COCO class IDs for vehicles ---
# These are the integer class IDs YOLOv8 uses internally
# You can verify with: model.names
VEHICLE_CLASSES = {
    2:  "car",
    3:  "motorcycle",
    5:  "bus",
    7:  "truck"
}

# --- Video ---

VIDEOS = {
    "Highway A"    : "4729132-hd_1920_1080_30fps.mp4",
    "Highway B"    : "9700994-uhd_3840_2160_30fps.mp4"
   
}
RESIZE_WIDTH = 1280              # Resize frame for consistent processing
RESIZE_HEIGHT = 720


# --- Zones ---
# Generated by zone_setup.py — do not edit manually
ZONES_PATH = "zones.json"

# Zone definitions used by zone_setup.py
# Each zone gets a label and a display color (BGR)
ZONE_DEFINITIONS = [
    {"label": "Entering City", "color": [0, 255, 0]},   # Green
    {"label": "Leaving City",  "color": [0, 0, 255]},   # Red
]

# --- SORT Tracker ---
MAX_AGE = 10        # Frames to keep a track alive with no matching detection
MIN_HITS = 2        # Frames a track must be seen before it's reported
IOU_THRESHOLD = 0.3 # Minimum overlap to match detection to existing track

# --- Traffic Density Thresholds ---
# Vehicles visible on screen at once
DENSITY_LOW    = 5
DENSITY_HIGH   = 15

# --- Display ---
SHOW_CONFIDENCE = True
SHOW_TRACK_ID   = True




